### ISSUE TITLE
When opening youtube in side-view it opens it in every window.

### ISSUE THREAD

**Issue by Joesv** [mozilla/side-view#307] opened 2018-07-13 19:10 UTC
I use a lot of different windows when I browse. I tried opening a Youtube (music) video in the side view panel and it opened on every single windows out of sync with the first window. There was a delay of roughly 100ms between some Windows.

**Comment by Softvision-CristinaBadescu** [comment] 2018-07-16 14:30
Thanks for reporting this issue. However, this is a dupe of #304 .

**Closed by Softvision-CristinaBadescu** 2018-07-16 14:30 UTC
