### ISSUE TITLE
[Shield] side-view shield study is not using shield-studies-addon-utils

### ISSUE THREAD

**Issue by pdehaan** [mozilla/side-view#323] opened 2018-08-30 16:46 UTC
https://github.com/mozilla/shield-studies-addon-utils

> Allows writing [Shield and Pioneer](https://wiki.mozilla.org/Firefox/Shield/Shield_Studies) ([Normandy](https://wiki.mozilla.org/Firefox/Shield#Normandy_-_User_Profile_Matching_and_Recipe_Deployment)) study WebExension Experiments correctly.

¯\\\_(ツ)\_/¯

**Comment by clouserw** [comment] 2018-09-04 16:17
duplicate of #313

**Closed by clouserw** 2018-09-04 16:17 UTC
