### ISSUE TITLE
Not being able to log in on twitter

### ISSUE THREAD

**Issue by ferminrp** [mozilla/side-view#275] opened 2018-06-05 19:26 UTC
For some reason I'm unable to log in on Twitter or Tweetdeck. Is anyone else experiencing this? I can log in just fine anywhere else.

**Comment by Softvision-CristinaBadescu** [comment] 2018-06-06 14:07
Hello,

I have tested this issue on latest Firefox Release 60.0.1, latest Nightly build 62.0a1 (Build ID: 20180606083531) and could not reproduce it. I have sent the "https://twitter.com/" page to the Side View sidebar and managed to log in my Twitter account without encountering any issue. 
Tested on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.

Can you give us more details such as what Firefox version and OS did you use when you encountered this issue?

Also, can you please retest this on the latest Firefox release using a new clean Firefox profile (https://goo.gl/AWo6h8), maybe even safe mode (https://goo.gl/AR5o9d), to eliminate custom settings as a possible cause, and report back the results?

Thanks.

**Comment by ferminrp** [comment] 2018-06-06 15:54
I'm on Windows 10. Firefox is up to date.

This happens when I try to use it on safe mode.

![twitter](https://user-images.githubusercontent.com/21282919/41050067-bf31b03c-6988-11e8-8444-b572d1eb5857.png)

**Comment by Softvision-CristinaBadescu** [comment] 2018-06-07 09:29
>This happens when I try to use it on safe mode.

This confuses me a little bit, because in the screenshot I see that some add-ons are enabled, including Side View. If you restart the browser in Safe Mode, all add-ons should be disabled.
There is the possibility that an add-on is in conflict with Side View. In order to verify this, can you please test if this issue is reproducible on a new Firefox profile (https://goo.gl/AWo6h8) without any other add-ons installed, but only Side View? 

If the issue is not reproducible with a new clean profile, can you please provide the list with the add-ons so I can test Side View with each add-on installed in order to find which one is in conflict.

Also, from the initial report I understood that you can not log in on Twitter, from the sidebar. Is that correct? I see that you are logged in your Twitter account, but a "Sorry, Twitter is taking too long to load" message is displayed. 

Thanks.

**Comment by JonHypersomniac** [comment] 2018-06-22 01:15
I have this issue as well. When I open Twitter it asks me to login, and so I did but it then asks me to login again, as if a cookie is not being set. I remember on a previous version of SideView I didn't had to login because I was already logged into the web Twitter.

**Comment by Softvision-CristinaBadescu** [comment] 2018-06-25 13:52
@JonHypersomniac , can you give us more details such as what Firefox version and OS did you use when you encountered this issue? Moreover, do you have the Firefox Multi-Account Container installed and Twitter is assigned to a container?
Also, can you please retest this on the latest Firefox release 60.0.2 using a new clean Firefox profile (https://goo.gl/AWo6h8), maybe even safe mode (https://goo.gl/AR5o9d), to eliminate custom settings as a possible cause, and report back the results?
Thanks.

**Comment by SoftVision-CosminMuntean** [comment] 2018-07-02 14:59
I'm closing this issue due to the lack of response from the reporter and @JonHypersomniac.
If anyone can still reproduce it, please add more information here and we will reopen the issue.

**Closed by SoftVision-CosminMuntean** 2018-07-02 14:59 UTC
