### ISSUE TITLE
If the focus is on the side view, tab-specific hotkeys should apply to it

### ISSUE THREAD

**Issue by towerofnix** [mozilla/side-view#319] opened 2018-08-29 12:58 UTC
Sorry for opening a slew of issues all at once! This one is a little crazier.

I often press ctrl-[ and ctrl-] to go back and forwards in history. There is no obvious way to go back in history on the side view pane; the buttons in the top left of the browser window apply to the main tab, the shortcut keys apply to the main pane, and even the right-click menu is missing the history buttons. The only way I found was to hold alt and use the scrollwheel.

Likewise, I press ctrl-+ and ctrl-(minus) to zoom in and out. I know zooming *does* work, contrary to #93, since hold control does let me zoom in. (And I'm on Linux, not Windows.) But the keyboard shortcuts for zooming don't work; they zoom the main pane.

**Comment by clouserw** [comment] 2018-09-04 16:16
closing this as a duplicate of the similar #312

**Closed by clouserw** 2018-09-04 16:16 UTC
